name: Deploy to All Domains
on:
  push:
    branches: main-ccns.2021
  schedule:
    - cron: "15 21 * * Wed,Sun"
jobs:
  deploy-all:
    strategy:
      fail-fast: false
      matrix:
        include:
          - inputs:
              CNAME: 'term.ccns.cc'
              DEFAULT_SITE: 'wsstelnet://ws.ccns.cc/bbs'
              DEV_PROXY_TARGET: 'https://ws.ccns.cc'
              DEV_PROXY_HEADER: 'https://term.ccns.cc'
            secrets-id:
              deploy-token: GITHUB_TOKEN
          - inputs:
              CNAME: 'term.ccns.ncku.edu.tw'
              DEFAULT_SITE: 'wsstelnet://ws.ccns.ncku.edu.tw/bbs'
              DEV_PROXY_TARGET: 'https://ws.ccns.ncku.edu.tw'
              DEV_PROXY_HEADER: 'https://term.ccns.ncku.edu.tw'
              deploy-repository-name: '${{ github.repository_owner }}/term.ccns.ncku.edu.tw'
              deploy-branch: main
            secrets-id:
              deploy-token: PTTCHROME_TOKEN
    uses: ./.github/workflows/deploy-ghpage.yml
    with:
      CNAME: ${{ matrix.CNAME }}
      DEFAULT_SITE: ${{ matrix.DEFAULT_SITE }}
      DEV_PROXY_TARGET: ${{ matrix.DEV_PROXY_TARGET }}
      DEV_PROXY_HEADER: ${{ matrix.DEV_PROXY_HEADER }}
      deploy-repository-name: ${{ matrix.deploy-repository-name }}
      deploy-branch: ${{ matrix.deploy-branch }}
    secrets:
      deploy-token: ${{ secrets[matrix.secrets-id.deploy-token] }}
